### ISSUE TITLE
Missing hitbox images

### ISSUE THREAD

**Issue by tommyalatalo** [yakiimoninja/baiken#1]
Some hitbox images seem to not be loaded when using Baiken; when I run `b.h giovanna 2D` the bot only posts the first of two images for the move.

**Comment by yakiimoninja** [comment]
Do you have a list of these moves?
The giovanna 2D was

**Comment by yakiimoninja** [comment]
Do you have a list of these moves?
Giovanna 2D will roll out with 0.4.4 and was probably an oversight on my part.

**Comment by tommyalatalo** [comment]
I haven't seen others fail this far actually, perhaps I was just unlucky to come across Gio 2D very soon into starting to use the bot. Thanks for fixing it, I'll report back if I stumble upon any more that are missing images.

**Comment by yakiimoninja** [comment]
There's actually a number of missing hotboxes I've found so far.
That's cause of dustloop not having any images for said moves when I was getting that data.
That being said I'll fix all of them for 0.4.4.

I had totally forgotten about that so thanks for reminding me.
