### ISSUE TITLE
b.update gives no feedback or is broken

### ISSUE THREAD

**Issue by altosys** [yakiimoninja/baiken#2]
I'm trying to do `b.update` on my server, but baiken is not responding with anything at all, so it's unclear whether the command doesn't work, or if something was updated but there just wasn't any confirmation for me as the user.

I'm currently trying to fetch `b.f hc 5H` and while the image is fetched properly the frame data table is empty

**Comment by yakiimoninja** [comment]
- The command `b.update` only works for owners. Did this to prevent spamming [dustloop.com](https://www.dustloop.com/) with unnecessary requests. So unless you are hosting your own instance, with your own bot and token running this source code, the command won't do anything.
&#x200B;
- If your are referring to this move, then this is displayed correctly. Cause a single press of `5H` just pulls out the gun.  \
But if you are looking for the actual shot, that would be the `b.f hc 236SH`.
<img src="https://user-images.githubusercontent.com/80072600/172003049-3a653d25-5a54-4e2a-b06b-3429bb09702a.PNG" width="204" height="323" />
 
You can always confirm if something is displayed correctly if you press the link above the embed and compare it to what dustloop shows.

**Comment by altosys** [comment]
You should probably update this in the readme, there is no mention that b.update only works for the owner if I'm not mistaken.

**Comment by yakiimoninja** [comment]
Will do so. Thank you!
