### ISSUE TITLE
Display move timeline

### ISSUE THREAD

**Issue by hissalht** [yakiimoninja/baiken#4]
Sometimes, it's useful to visualize the "timeline" of a move.

On dustloop, it looks like this (this is Potemkin's 5P) :

<img width="252" alt="Example of move timeline" src="https://user-images.githubusercontent.com/7683740/209680801-b7211bfc-3c01-49d9-b9a8-3549817f1c44.png">

I saw someone use colored heart emojis on Discord to help visualize something they explained.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/7683740/209682034-ec233599-3451-412e-be56-369d3dfc2416.png">

It could also be done with squares or circle emojis I guess :

```
🟩🟩🟩🟩🟥🟥🟥🟥🟥🟦🟦🟦🟦🟦🟦

🟢🟢🟢🟢🔴🔴🔴🔴🔴🔵🔵🔵🔵🔵🔵
```

I think would be cool to get something similar when using the `/frames` command or maybe a new `/timeline` command.

**Comment by yakiimoninja** [comment]
Sounds like a cool idea. Maybe I'll give it a go.

**Comment by yakiimoninja** [comment]
How do you feel about this kind of frame display?
I figured that having it as a continuous line would be too long and unreadble.
So I split it into separate lines.
![2023-01-15_19-52](https://user-images.githubusercontent.com/80072600/212563953-08df1c70-6bac-40cc-824e-57c4216fa957.png)

**Comment by yakiimoninja** [comment]
Closing as implemented with 0.10.0

**Comment by hissalht** [comment]
Damn, that's sick
