### ISSUE TITLE
[SUGGESTION] Check if a missing move exists with levels instead.

### ISSUE THREAD

**Issue by AdrianRBerg** [yakiimoninja/baiken#5]
Had an issue yesterday where I tried to get the hitboxes of Nagoriyuki's j.S, but after multiple attempts, the bot wouldn't recognize it. A check on /moves revealed that the move existed as a level version, but not standalone.

The suggestion is that if i do `/hitboxes Nago j.S`, it should check if `j.S Level 1` exists if `j.S` doesn't. I'm willing to fork and help write the code for this, as I think it would be a nice quality of life feature.

**Comment by yakiimoninja** [comment]
That's an easy fix.
I just forgot to create aliases for jS and its levels.
Thanks for bringing it to my attention.

Closing as it will be fixed for patch 0.11.0
